[package]
name = "silentjack-rs"
version = "0.1.0"
authors = ["Marks Polakovs <github@markspolakovs.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jack = "0.6"
clap = "2.33.0"